data:
  image: alpine:latest
  command: /bin/true
  volumes:
    - ./neos-development-distribution:/var/www/neos
    - ./flow-development-distribution:/var/www/flow

neos-db:
  image: 'mariadb:latest'
  command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=neos

flow-db:
  image: 'mariadb:latest'
  command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=flow

app:
  build: 'docker/app'
  volumes_from:
    - data
  links:
    - neos-db
    - flow-db
#    - elasticsearch
  environment:
    - WWW_USER_ID=1001
#    - WWW_USER=neos
#    - FLOW_CONTEXT=Development

web:
  build: 'docker/web'
  ports:
    - "80:80"
  volumes_from:
    - data
  links:
    - app
#  environment:
#    - NEOS_HOST=neos.dev
#    - FLOW_HOST=flow.dev

#elasticsearch:
#  image: 'elasticsearch:1.7-alpine'
#  volumes:
#    - ./docker/elasticsearch/1.7/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

#elasticsearch:
#  image: 'elasticsearch:2.4-alpine'
#  volumes:
#    - ./docker/elasticsearch/2.4/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#    - ./docker/elasticsearch/2.4/java.policy:/home/elasticsearch/.java.policy:ro
