data:
  image: alpine:latest
  command: /bin/true
  volumes:
    - ./neos-development-distribution:/var/www/neos-dev
    - ./flow-development-distribution:/var/www/flow-dev
    - ./neos-base-distribution:/var/www/neos-base
    - ./flow-base-distribution:/var/www/flow-base

db-neos-dev:
  image: 'mariadb:latest'
  command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=neos-dev

db-flow-dev:
  image: 'mariadb:latest'
  command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=flow-dev

db-neos-base:
  image: 'mariadb:latest'
  command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=neos-base

db-flow-base:
  image: 'mariadb:latest'
  command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=flow-base

app:
  build: 'docker/app'
  volumes_from:
    - data
  links:
    - db-neos-dev
    - db-flow-dev
    - db-neos-base
    - db-flow-base
#    - elasticsearch
  environment:
    - WWW_USER_ID=1001
#    - WWW_USER=neos
#    - FLOW_CONTEXT=Development

web:
  build: 'docker/web'
  ports:
    - "80:80"
  volumes_from:
    - data
  links:
    - app
#  environment:
#    - NEOS_DEV_HOST=neos.dev
#    - FLOW_DEV_HOST=flow.dev
#    - NEOS_BASE_HOST=neos.base
#    - FLOW_BASE_HOST=flow.base

#elasticsearch:
#  image: 'elasticsearch:1.7-alpine'
#  volumes:
#    - ./docker/elasticsearch/1.7/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

#elasticsearch:
#  image: 'elasticsearch:2.4-alpine'
#  volumes:
#    - ./docker/elasticsearch/2.4/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#    - ./docker/elasticsearch/2.4/java.policy:/home/elasticsearch/.java.policy:ro
